name: Daily GitHub PR Snapshot

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes for testing
  workflow_dispatch:       # manual trigger

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env file for token
        run: echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" > .env

      - name: Run PR report script
        run: python pr_all_repos_daily_snapshot.py
